project_id = "cafuseuxbixttnlixhxq"

[functions.chat]
verify_jwt = false

[functions.rag-search]
verify_jwt = false

[functions.rag-ingest]
verify_jwt = true

[functions.rag-reindex]
verify_jwt = true

[functions.submit-contact-form]
verify_jwt = false

[functions.generate-slots]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true
